### ISSUE TITLE
KESC

### ISSUE THREAD

**Issue by ryu12332** [InfiniteFlightAirportEditing/Navigation#454] opened 2017-05-24 17:41 UTC
9/27 tweaked.

**Comment by bavAVIA** [comment] 2017-05-24 17:42
Please only create ILS issues when the airport has been approved and taken into the repository. Thanks.

**Comment by ItsW1ll** [comment] 2017-06-11 20:18
@bavAVIA has the airport been committed?

**Comment by brunocr98** [comment] 2017-06-11 20:44
The issue is closed, so I think yes. 

https://github.com/InfiniteFlightAirportEditing/Airports/issues/1911

**Comment by Adrien-Z** [comment] 2017-07-17 14:04
Fixed by @ItsW1ll in 0b4e4c2.

**Closed by Adrien-Z** 2017-07-17 14:04 UTC
Labels: ILS
